name: WFLI Token Monitor
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run token monitor
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          DESTINATION_ADDRESS: ${{ secrets.DESTINATION_ADDRESS }}
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          TOKEN_ADDRESS: ${{ secrets.TOKEN_ADDRESS }}
        run: node scripts/check-transfers.js

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 WFLI Monitor Failed',
              body: `Workflow run failed: ${context.runId}`
            })